name: Upload Glue Code
run-name: Upload Glue 

on:
  workflow_call:
    inputs:
      github-sha:
        description: 'GitHub SHA to be used as a part of S3 Bucket key.'
        required: true
        type: string
    outputs:
      glue-code-upload-status: 
        description: 'Specifies the status of Lambda code upload.'
        value: ${{ jobs.package.outputs.lambda-code-upload-status }}
    secrets:
      aws-region:
        required: true
      aws-role-arn:
        required: true
      code-repository-s3-bucket:
        required: true
      kms-key-arn:
        required: true
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  package:
    name: "Upload Glue Code"
    outputs:
      glue-code-upload-status: ${{ steps.upload-glue-code-to-s3.outputs.glue-code-upload-status }}
    runs-on: ubuntu-latest #[self-hosted, Linux, X64, Subhamay-GH-Runner]
    environment: ${{ inputs.github-env }}
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:

      - name: Print the job input parameters
        id: print-job-input-params
        run: |
          echo "Input :: GitHub SHA                : ${{ inputs.github-sha }}"

      ####################################################
      ########## Checkout Code
      ####################################################
      - name: Git checkout
        id: git-checkout
        uses: actions/checkout@main

      ##############################################################################################
      ########## Configure AWS Credentials
      ##############################################################################################
      - name: Configure AWS credentials from AWS account
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.aws-role-arn }}
          aws-region: ${{ secrets.aws-region }}
          role-session-name: github-aws-cloudformation-oidc

      ###############################################################################################
      ########### Upload Lambda to S3 repository Bucket
      ###############################################################################################
      - name: Upload Glue code to S3 Repository Bucket
        id: upload-glue-code-to-s3
        env:
          CODE_REPOSITORY_S3_BUCKET: ${{ secrets.code-repository-s3-bucket }}
          KMS_KEY_ARN: ${{ secrets.kms-key-arn }}
        run: |
          echo "Uploading Glue code to S3 repository"
          ## Upload Glue Code to repository S3 Bucket
          aws s3 cp ${{ github.workspace }}/${{ inputs.github-sha }}/glue-code/ s3://${{ secrets.code-repository-s3-bucket }}/${{ github.event.repository.name }}/${{ inputs.github-sha }}/glue-code/ --sse "aws:kms" \
          --sse-kms-key-id ${{ secrets.kms-key-arn }} --storage-class GLACIER_IR --exclude "*" --include "*.py"
          echo "glue-code-upload-status=GLUE_CODE_UPLOAD_SUCCESSFUL" >> $GITHUB_OUTPUT

      - name: Print the job output parameters
        id: print-job-output-params
        run: |
          echo "Output :: Lambda Glue Code Upload Status : ${{ steps.upload-glue-code-to-s3.outputs.glue-code-upload-status }}"
