name: Detect Drift

'on':
  workflow_call:
    secrets:
      git-token:
        required: true

permissions:
  id-token: write # This is required for aws oidc connection
  contents: write # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR  
  issues: write

jobs:
  detect-drift:
    name: "Terraform Plan (prod)"
    uses: ./.github/workflows/tf-plan.yaml
    with:
      github-env: prod
      tfvar-file: prod.terraform.tfvars
      issue-number: "0"
      aws-region: ${{ vars.AWS_REGION }}
      aws-role-arn: ${{ vars.PROD_AWS_ROLE_ARN }}
      kms-key-arn: ${{ vars.PROD_AWS_KMS_KEY_ARN }}
      aws-tf-state-bucket-name: ${{ vars.PROD_AWS_TF_STATE_BUCKET_NAME }}
  create-issue:
    name: "Create Issue"
    needs: detect-drift
    if: ${{ needs.detect-drift.outputs.change-detected == 'true' }}
    uses: ./.github/workflows/create-issue.yaml
    with:
      git-token: ${{ secrets.git-token }}
      issue-title: "Drift Detected in prod"
      issue-body: "Drift detected in prod. Please review and take necessary action."
      issue-assignee: "github-actions[bot]"
      issue-labels: "drift"
      issue-project: "Drift Detection"
      issue-milestone: "Drift Detection"
      issue-assignees: "github-actions[bot]"
      issue-assignees: "github-actions[bot]"
      issue-assignees: "github-actions[bot]"
