name: Terraform Plan

on:
  workflow_call:

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR
 
jobs:
  update-reviewer:
    name: "Update Reviewer(s) (${{ inputs.github-env }})"
    runs-on: ubuntu-latest
    environment: ${{ inputs.github-env }}
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:

      - name: Update Environment (prod) and remove reviewers and wait_timer
        id: update-environment
        uses: octokit/request-action@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: PUT /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/environments/prod/protection_rules
          mediaType: |
            format: raw
          wait_timer: null
          reviewers: []
          # body: |
          #   {
          #     "wait_timer": null,
          #     "reviewers": []
          #   }




          